title: 相册
author: Vvida
email: 
description: >-
  存放一些照片

social:
  github: Vvida
  #linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
